[package]
name = "backup-nf"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.1"
ratatui-explorer = "0.1.1"
serde = {version = "1.0.197", features = ["derive"]}
toml = "0.8.10"
tui-textarea = "0.4.0"
